export const FETCH_GROUND_HIT='FETCH_GROUND_HIT'
export const FETCH_GROUND_RAND='FETCH_GROUND_RAND'
export const FETCH_GROUND_LIST='FETCH_GROUND_LIST'
export const FETCH_GROUND_DETAIL='FETCH_GROUND_DETAIL'

export const FETCH_BOARD_LIST='FETCH_BOARD_LIST'
export const FETCH_BOARD_DETAIL='FETCH_BOARD_DETAIL'
export const FETCH_BOARD_INSERT='FETCH_BOARD_INSERT'
export const FETCH_BOARD_UPDATE='FETCH_BOARD_UPDATE'
export const FETCH_BOARD_DELETE='FETCH_BOARD_DELETE'



